included: # 执行 linting 时包含的路径。如果出现这个 `--path` 会被忽略。
    - Ketchup

excluded: # 执行 linting 时忽略的路径。 优先级比 `included` 更高。
    - Pods
    - Resources
    
disabled_rules: # 执行时排除掉的规则
    - colon
    - comma
    - control_statement
    - line_length
    - file_length
    - type_name
    - trailing_whitespace
    - trailing_newline
    - identifier_name
    - force_cast
    - shorthand_operator
    - function_body_length
    - function_parameter_count
    - large_tuple
    - type_body_length
    - cyclomatic_complexity
    - void_return
    - unused_closure_parameter
    - empty_enum_arguments
    - syntactic_sugar
    - force_try
    - vertical_whitespace
    - multiple_closures_with_trailing_closure
    - notification_center_detachment
    - computed_accessors_order
    - trailing_closure
    - private_over_fileprivate

nesting: # 嵌套最多3层, 否则会触发嵌套违规警告
    type_level: 3

line_length: 110
